[project]
name = "42-achievements-piscine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.0",
    "pydantic>=2.13.4",
    "rich>=15.0.0",
    "ruff>=0.16.0",
]
